name: OSS #自动化的名称
on:
  push: # push的时候触发
    branches: # 那些分支需要触发
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master #软件市场的名称
      with: # 参数
        submodules: true
    # hugo build static files
    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.75.1'
        extended: true
    - name: Build
      run: hugo --minify
    # push to Aliyun OSS
    - uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: "oss-cn-hangzhou.aliyuncs.com"
        access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
    - name: Deply To OSS
      run: ossutil cp public oss://agou-ops-2 -rf